-- Drive links for the safety data sheets imported in 0007.
--
-- The register stores filenames only; these are the matching files in the
-- lab's shared SDS folder, resolved by exact filename. Stored per reagent so
-- the viewer can open the sheet directly instead of sending someone to hunt
-- through a folder while holding a chemical.
--
-- Links are the /view form. SdsModal rewrites them to Drive's /preview for
-- embedding and keeps this original as the "open in Drive" fallback.

UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1bb-DCcD0w4ntxB-zTaZ8wlapExiaZ_V_/view' WHERE lower(sds_file) = '6c54.58_conc. wash buffer.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1YE2jH9nCvN7iDoRPCqXuv5jrhkg8_jdn/view' WHERE lower(sds_file) = '8k25.04_intact pth calibrator.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1m8PjLwNMWvE6RLMeZPSwCOsKRa7WyuNq/view' WHERE lower(sds_file) = '8k25.13_intact pth control.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1qUzuqlnUTC0Xeq6YGomiS7PIg2OuyXHK/view' WHERE lower(sds_file) = '8k25.28_intact pth reagent.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/10UBvcnQZFvMpXNKjxSgJdAJsMaZVZvt3/view' WHERE lower(sds_file) = 'acid probe wash.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1KkBjaYMvI0M50MINPJNn8jaG8IkQ3NnK/view' WHERE lower(sds_file) = 'actin fs.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1JC_e5oI8R7Ti1acuo5uqF53xGMtR_C5M/view' WHERE lower(sds_file) = 'alinity afp cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1brEZJhTD9XQCLyrHNW9LBWe66o5nxqFY/view' WHERE lower(sds_file) = 'alinity afp msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1XwuBoMs9i7fywA4wYffCuZ5tJ-JbcR7I/view' WHERE lower(sds_file) = 'alinity albumin2 msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1URHqJYeH0wk2UhvHyaSbEWjGMpsVKye8/view' WHERE lower(sds_file) = 'alinity alp2 msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1sGMe2qN20DiuOsX3i-Q-uRpj6jDOURWz/view' WHERE lower(sds_file) = 'alinity alt2 msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1Wce41VR5bwo0J0kXK5k9e5pZu9oJwGRj/view' WHERE lower(sds_file) = 'alinity amylase2 msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1kSJ1BTmcaxoF5iPz_LVf_S3Z8rKHzJVv/view' WHERE lower(sds_file) = 'alinity anti hcv cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1sLY41lHKycLTM-6a6-sYSHvIIzsW_XVD/view' WHERE lower(sds_file) = 'alinity anti-hbc cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1cI-m4A1inr7Fzc9keV_DW7t2Gsz45gJA/view' WHERE lower(sds_file) = 'alinity anti-hbc control msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1osvjao5VY78DFDncKplOE55iWFGfqXtH/view' WHERE lower(sds_file) = 'alinity anti-hbc igm cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1MLpM_tfyogzUZ1EHTSFkH9vi40en5cwD/view' WHERE lower(sds_file) = 'alinity anti-hbc igm control msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1EGMn9toDfK-dAGdvmtAPE1rXnqy3shhd/view' WHERE lower(sds_file) = 'alinity anti-hbc igm msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1j87VRZ5-BfOiYE47MJaSnzecv7b_Ue5k/view' WHERE lower(sds_file) = 'alinity anti-hbc msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/13LbFvirSyK0keCJLrs7_orfjyBRBOcYG/view' WHERE lower(sds_file) = 'alinity anti-hbe cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1nCf6npEh9UU8HsYuHYqUxk_EZdVybYd4/view' WHERE lower(sds_file) = 'alinity anti-hbe control msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1HqxVZEW7BkBDfmdjZbTwenCgLLQG1-lW/view' WHERE lower(sds_file) = 'alinity anti-hbe msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1Z5CDkGQW8trTWDpFZF6FcKFyqcAkoiLg/view' WHERE lower(sds_file) = 'alinity anti-hbs cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1jGGc2CzKwoaNVMhHjjbJGBSQZQttJzMK/view' WHERE lower(sds_file) = 'alinity anti-hbs control msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1060CUMy4ifectX0t3sGLEhXC1Pxue8Yf/view' WHERE lower(sds_file) = 'alinity anti-hbs msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1pZ5pAyb82bleFkfMedCdTVii3MaGwlfh/view' WHERE lower(sds_file) = 'alinity anti-hcv control msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1GCe30--NHPbq_s6MbnHE06ZypggqJ3Kj/view' WHERE lower(sds_file) = 'alinity anti-hcv msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1X8v71NuPxfNh7CZodL4iXEJ0fefHcSDA/view' WHERE lower(sds_file) = 'alinity ast2 msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1mkmWyga_lggDpLIH-99PtOZLbLNkBbHa/view' WHERE lower(sds_file) = 'alinity bilirubin calibrator msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/14PoghBZ6PjcuQTSF6wzOXnld-6nIRZE5/view' WHERE lower(sds_file) = 'alinity bun msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1jK_gLyfsGl6H26DIHms2gALDwBtr653O/view' WHERE lower(sds_file) = 'alinity c ict reference msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1aMTGXi6fUOKzHJgm2YdyXuOlcyEmCxYe/view' WHERE lower(sds_file) = 'alinity c ict sample diluent msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1Ms48Ez1VxfIskb9mX3aGRflkMhjWBo3E/view' WHERE lower(sds_file) = 'alinity calcium msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1qXrBXcYXVv1H9wVU4URn31Bm0mUlKLaj/view' WHERE lower(sds_file) = 'alinity cea cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/146YOL75Lc5AF_eiJbA_Z6v6Dki1283Yc/view' WHERE lower(sds_file) = 'alinity cea msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1NnNwQfuz3gLC0B7EFKhlElLJh1MNRaNn/view' WHERE lower(sds_file) = 'alinity cholesterol2 msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1Lmo2bD9H3AqxVzz_zALlxMbEibx1DTVb/view' WHERE lower(sds_file) = 'alinity ck msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/16pxyYLCuIX488NSETrWrYAKGv1VHJMMq/view' WHERE lower(sds_file) = 'alinity clinical chemistry calibrator msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1HvCdQ3jlngkbE26PXz1tO1bMal3Sy67J/view' WHERE lower(sds_file) = 'alinity co2 calibrator msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1KJHvgiC7P4Tq88RbIZOWC91z4ldDzOIR/view' WHERE lower(sds_file) = 'alinity co2 msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1RiNar2FIsmJTwcE7vQvBJ8-rUuEK5ASr/view' WHERE lower(sds_file) = 'alinity consolidated calibrator msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1fkFmkhRaYe-ls16a_pNod9vnW9WcpBPB/view' WHERE lower(sds_file) = 'alinity creatinine msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1df95U1H8xrujWSXjqXkve3eoHorErRaB/view' WHERE lower(sds_file) = 'alinity crp calibrator msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1OqGanUkKNs1-Syd6eIEYnKWBZ_DXgWaG/view' WHERE lower(sds_file) = 'alinity crp msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1mWaeCme01GlsihnclbqmZfwW6siv-JC1/view' WHERE lower(sds_file) = 'alinity direct bilirubin msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1wLScKJCOjSuB121IYPHVJdelQ67bDN7F/view' WHERE lower(sds_file) = 'alinity ferritin cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1mFn_vk0YUVizkqmz00RPK0KBlkDD-ifs/view' WHERE lower(sds_file) = 'alinity ferritin msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1t-Tb_Wi3AtUnupXmxbA64M4g8CfBxxXn/view' WHERE lower(sds_file) = 'alinity free psa cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1FB2_ReZyHJx9rDADHVs3FV1uOzkQVOe2/view' WHERE lower(sds_file) = 'alinity free psa msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1g6CIjBClIuDUh8ymdHrlmitNkAx29px-/view' WHERE lower(sds_file) = 'alinity free t3 cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1KrItfH-QYqniMP4musJIcEHpgtatc-Dy/view' WHERE lower(sds_file) = 'alinity free t3 msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1K1x2ENXHOMeYasEYjsr0mydVF4K3h9LJ/view' WHERE lower(sds_file) = 'alinity free t4 cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1lYjTh_lUuEZwWkarPQ9KLTRqw6hne_iE/view' WHERE lower(sds_file) = 'alinity free t4 msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1uoTnG-St4SL_ldifvWSb9-RxWgAmiAok/view' WHERE lower(sds_file) = 'alinity ggt2 msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1OkGtZcqqEGUiD_MNyQ3AHZyZdPVsanjP/view' WHERE lower(sds_file) = 'alinity glucose msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1BF4xYTBtx1yiXfKOOeeWkXt7_6BgT4r_/view' WHERE lower(sds_file) = 'alinity hav igg cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/14vUaklVFB0TQEXBBRJXIxxvEMYrRRNVl/view' WHERE lower(sds_file) = 'alinity hav igg control msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1IXsDjDOg50IGDl670MljvJiczHs2BKOJ/view' WHERE lower(sds_file) = 'alinity hav igg msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1Ty0dZevOquDR34PTGJed1mEAhjP03Gux/view' WHERE lower(sds_file) = 'alinity hav igm cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1OSGhIoRixpXc_fL6DxKTELRZ1QH5dJMw/view' WHERE lower(sds_file) = 'alinity hav igm control msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1GnlwCwjYlsJhJCYn1qsY6hMBbY9sn_ee/view' WHERE lower(sds_file) = 'alinity hav igm msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1oDg6Ws6PlABK82-qsi4BrcVgps8CYEYI/view' WHERE lower(sds_file) = 'alinity hba1c msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1WQiT0VqMB0CuJReciAqoEx2E5hntek-y/view' WHERE lower(sds_file) = 'alinity hbeag cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1fLfaOsQ_KGZPd50qYrNCRe1MKzzIsy4k/view' WHERE lower(sds_file) = 'alinity hbeag control msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1Nkges2d_fBxO1bOwfl8JakSRtJm5SR5y/view' WHERE lower(sds_file) = 'alinity hbeag msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1-CjoqsRwRc8uVuTwWSx7ilKYkGbaejZW/view' WHERE lower(sds_file) = 'alinity hbsag quali cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1ugJhfXbBhM0l0RfsSsKkflNAADICav0V/view' WHERE lower(sds_file) = 'alinity hbsag quali cotrol msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/192hiDoNhsG6uqeTUGhZAgEcYKfPaUFKz/view' WHERE lower(sds_file) = 'alinity hbsag quali msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1mBQ_rvXSivCCZB7if6mcq53osIVt-zsC/view' WHERE lower(sds_file) = 'alinity hbsag quanti cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1Onyf9w5wuapPYSb8IhxGklm_Dj1ph1dW/view' WHERE lower(sds_file) = 'alinity hbsag quanti control msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1o1MNvgnYgtc9WjeVqqyK7ZsKFXy8CLYr/view' WHERE lower(sds_file) = 'alinity hbsag quanti msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1sfv3py9PN4dgeyv-vsqjNwrsrRfce_tZ/view' WHERE lower(sds_file) = 'alinity hdl msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1dONKXPfp-7JBzaurJvv0bkc3J9m8YybY/view' WHERE lower(sds_file) = 'alinity hemoglobin a1c cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1KhFCNT_uimyz9apsxOrf9VM4Kni4gL7-/view' WHERE lower(sds_file) = 'alinity hemoglobin a1c control msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1epk-bFr7MnP5ou9udS1LWqYDg1ESHs_o/view' WHERE lower(sds_file) = 'alinity hscrp calibrator msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1jP7In0y7Wl_25mk7csvqxG21vOTv2AkO/view' WHERE lower(sds_file) = 'alinity hscrp control msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1TLq7XN7hcJ2EWJAjSkrRi3a4FdABVRs8/view' WHERE lower(sds_file) = 'alinity ict serum calibrator msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/18avePIaXAnoETOlYXvgvUHGHqBo4MwSK/view' WHERE lower(sds_file) = 'alinity ict urine calibrator msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1Rmk5zy3d_wfyNDozTqKJqJnp64fnWCjE/view' WHERE lower(sds_file) = 'alinity iron2 msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1nrGsufVPkk3zWssrP-5fkpV_SjSWGwfu/view' WHERE lower(sds_file) = 'alinity ldh2 msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1_GI7EnDIuK87aKM-JswsQ2F2HUsaiKXa/view' WHERE lower(sds_file) = 'alinity ldl msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1MLCo-coZFhBXcgGCqyAQDK7KU9dvjuLG/view' WHERE lower(sds_file) = 'alinity lipase cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1TL4EznZXeXrEm_AD8Exs0gmsfL-u2OgL/view' WHERE lower(sds_file) = 'alinity lipase msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1INVplk4xSKUrDuXgdnZx6LC7ASFlZSJf/view' WHERE lower(sds_file) = 'alinity lipid multiconstituent cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1kCUidaNc5WHiwC96LvoRldQDx1REe7P7/view' WHERE lower(sds_file) = 'alinity magnesium msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1oxOW6PYp6aHzJ3JyOc0DceWr19TH1vUY/view' WHERE lower(sds_file) = 'alinity microalbumin calibrator msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/177L7dJwGDGwETgVDkBw5c2yVTbSNQ-wZ/view' WHERE lower(sds_file) = 'alinity microalbumin msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1wGd3QaAtkfvjqOCNSA3xm78Y18ANTNac/view' WHERE lower(sds_file) = 'alinity multiconstituent calibrator msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1md0XqhlhrjKakxj7h_eqDB8zsdbZJq7A/view' WHERE lower(sds_file) = 'alinity phos2 msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1jB5EkSw4c7KHvJtIEny-BI8q77OFTKDg/view' WHERE lower(sds_file) = 'alinity protein (urinecsf) msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1DfM2b04urKx76b4b45zc1jFx8UGpoQAb/view' WHERE lower(sds_file) = 'alinity psa msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1hnukvb_dBwwcrXzsVLvUMnCxCfNjGT9N/view' WHERE lower(sds_file) = 'alinity total bilirubin msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1GD65vtcKzSlmwUo0oDHRSCVhEr0sGq73/view' WHERE lower(sds_file) = 'alinity total protein2 msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1Qroc3zYq4P9S4xjS5snrX7ZSdWL2mfOL/view' WHERE lower(sds_file) = 'alinity total psa cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1XF9FVCEKYan6t5eUAkibX6GmxAdfINqA/view' WHERE lower(sds_file) = 'alinity total t3 cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1U9O8qzc_YLZgnvv99Cb6QUVVFCR93Jnl/view' WHERE lower(sds_file) = 'alinity total t3 msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1qV8ziBJ723XDdbZm7aMc7IP3lg2qWH_C/view' WHERE lower(sds_file) = 'alinity total t4 cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1VFCxOnD4OzNuyzDYm_srVPjXvl8NWl4e/view' WHERE lower(sds_file) = 'alinity total t4 msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1pEB1lq7uaiy8lEtTchvpfyBm6FkkwUnX/view' WHERE lower(sds_file) = 'alinity triglycerides2 msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1WY32AjhckdCR_68vGzt2JC4wJNUlKIAu/view' WHERE lower(sds_file) = 'alinity tsh cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1iAaqFtmDUdPLhSyRxCfcgeU25_KK78oD/view' WHERE lower(sds_file) = 'alinity tsh msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1nC-vXFy6IU1mT1CemHcksAMkk9YE23_H/view' WHERE lower(sds_file) = 'alinity uibc calibrator msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1ElO6hIQo5vBC7wqgXBTJ-kXoigDYjvqI/view' WHERE lower(sds_file) = 'alinity uibc msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1b7FisBrHCRHXW931N5-mK3Y4wxvL5Sbx/view' WHERE lower(sds_file) = 'alinity uric acid2 msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1rQvrWC4CZjJwcqXU4TNLSZYSqdoR87W_/view' WHERE lower(sds_file) = 'alinity urinecsf protein cal msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1-0QQqme3TndILxeDxkXSJw36B0v6Vn2x/view' WHERE lower(sds_file) = 'ca clean i.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1nUIhsq0ZvHh5mtcjzXoPfnlWLmDbgTZk/view' WHERE lower(sds_file) = 'cacl2.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1CJKTBpd1kHpp-670BoqByz4Uh6A6qHlp/view' WHERE lower(sds_file) = 'citrol 2.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1mvz4nUeGD7PGdTAorN7K3avWf0XFaIIz/view' WHERE lower(sds_file) = 'control n.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1H0oDOZ-Py-opW9VU1PZ87YLpXQzWXS3U/view' WHERE lower(sds_file) = 'control p.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1umJ9_4tfUOFFc-5r6xYiA9kJiVw8i3WC/view' WHERE lower(sds_file) = 'detergent a.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1ZD7y58QE2-IjZUavj1Mi2UhHCYjx4cpN/view' WHERE lower(sds_file) = 'detergent b.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1yUuTSMq7es2v1j2vPbwNDDbiLhkgVItP/view' WHERE lower(sds_file) = 'esr control_10435-en-esr-control-cube-msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1RQcAnlqialt9ja8N-gRe4cooHy-m5khM/view' WHERE lower(sds_file) = 'hiv ag ab combo calibrator.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1-5p0yDIkFY-6maHVICqdL8VDHJsPMx94/view' WHERE lower(sds_file) = 'hiv ag ab combo controls.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1ujlTvmddCc671bmgVpbhLSgk8QIOhFC6/view' WHERE lower(sds_file) = 'hiv ag ab combo reagent kit.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1DDMJXdNQf0sWpNxeZBI62sXCQdv3BWVe/view' WHERE lower(sds_file) = 'maintenance solution kit .pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1bGsmaqdntih3J2VDAVHFjEitsIrf70t7/view' WHERE lower(sds_file) = 'msds di potassium_thai version.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1Ps7oNEHazJcv88MLkPHvYdtxAJ7GfQQ5/view' WHERE lower(sds_file) = 'msds potassium phospate_thai version.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1PxtWEjDZBgPy6i-kIVpi8pGTsRfTMZZQ/view' WHERE lower(sds_file) = 'msds wright-giemsa eng ver..pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1noCIynu7qazwW7MBP53p5fpvmMnf5PIU/view' WHERE lower(sds_file) = 'msds-ca1311-methanol.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1sLUqoMQfp3AXRMWtahBrJLlxtwkTSHMD/view' WHERE lower(sds_file) = 'msds_bc-ret_v3.0.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1Dl_cT01o3f1FmYIZTXxFKb7z5EG8-J_6/view' WHERE lower(sds_file) = 'msds_immersion oil merck_thai version.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1b7tXcTGBiZxiyB0WNmG13QzNfjP8Yb18/view' WHERE lower(sds_file) = 'msds_m-6dr diluent_thai version.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1TEai-Yvqame9cZlDxBJv7QHHKs4B6q52/view' WHERE lower(sds_file) = 'msds_m-6fd dye_thai version.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/14eU0V8uXRmXsG3EYQ10b3Uyxc4OgE93a/view' WHERE lower(sds_file) = 'msds_m-6fn dye_thai version.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1vP3xEQayVuYpofcxFWGoXsvJW7nS2Op-/view' WHERE lower(sds_file) = 'msds_m-6fr dye_thai version.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1L0pvqzFEsVvRnujlnbVqaLmVowpXJ1DV/view' WHERE lower(sds_file) = 'msds_m-6ld lyse_thai version.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1H4BNwCPoSFG_jNNTxiGEeW61NrbvHsFh/view' WHERE lower(sds_file) = 'msds_m-6lh lyse_thai version.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1pqfsl_lqIzIPoSu6YqOHNZ2VBaqsd91m/view' WHERE lower(sds_file) = 'msds_m-6ln lyse_thai version.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1zdLxCO_lUJiaAE5clqmkRynNxKlAQoua/view' WHERE lower(sds_file) = 'msds_probe cleanser_thai version.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1jo77zuR4aWqxxaiEWunPKFm0va0OCgsk/view' WHERE lower(sds_file) = 'multichem ia plus abbott msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1oKfP1YQ5A7vlLQie8mrBeQkFt6n5aRb0/view' WHERE lower(sds_file) = 'multichem ia plus abbott msds.v6 en zl_architect.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1lvXHwYi7G1PFryMs4OcaURI61TtPJ7Oz/view' WHERE lower(sds_file) = 'multichem s plus assayed abbott msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1nH2rTsaU3-3Q3N5U4Kyikg2Iln7D0fgV/view' WHERE lower(sds_file) = 'multichem u abbott msds.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1AePF8Z_vTsDcRRayqatbouMblZWqAmuJ/view' WHERE lower(sds_file) = 'pre-trigger solution.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1ont0nkn79Z5PuFOhnf4PUlg5sfp_7pxP/view' WHERE lower(sds_file) = 'probe conditioning solution.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1DgC0g1G6UBGa8ZNlzrk5fqeocEossB3F/view' WHERE lower(sds_file) = 'safety data sheet of bc-6d control.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1f_zndWEX3e480ioBrMi_7Ty3VKkt_9b6/view' WHERE lower(sds_file) = 'sc-cal plus msds 3.0.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/18u-0UzksewPuhY-XASz7BlqwfwGdwWRm/view' WHERE lower(sds_file) = 'syphilis tp calibrator.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1ELAChufeyBf8Q0T4OI0tR6HPexBMXPgG/view' WHERE lower(sds_file) = 'syphilis tp controls.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1a2e8LQCxU5ostRg_YgLtiaklpHk1-BHT/view' WHERE lower(sds_file) = 'syphilis tp reagent.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1fpJOCMgem4PEA8uURxStknHBGX-PLqrq/view' WHERE lower(sds_file) = 'thromborel s.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/1hgXLptb9FMet4nJqDxNqzZvPM1jw1tH0/view' WHERE lower(sds_file) = 'trigger solution.pdf';
UPDATE reagents SET sds_url = 'https://drive.google.com/file/d/10uicIgTVEdUTLcc0i--8CoRl4H-EtjKD/view' WHERE lower(sds_file) = 'washing solution .pdf';
